# 미리봄 레시피 사이트 데이터. 새 릴스가 나오면 VOLUMES 맨 앞에 하나 추가하고 build.py 실행.

VOLUMES = [
    {
        'slug': '19',
        'reel': 19,
        'type': 'guide',
        'part': 'HOW TO',
        'title': '손바닥 위 포켓베이비 만드는 법',
        'short': '사진 한 장 + ChatGPT + Kling',
        'lede': '조회수 수백만이 나오는 손바닥 위 아기 영상, 사진 한 장으로 만드는 법을 프롬프트까지 그대로 정리했어요. 2026년 10월 기준이에요.',
        'hero': '19-hero',
        'hero_shape': 'tall',
        'hero_tag': 'IG @tasyajijavadze',
        'facts': [('1장', '사진'), ('3', '단계'), ('무료', '720p 가능')],
        'ctas': [('만드는 법 보기', '#s1'), ('Kling 설정값', '#price')],
        'steps_title': '만드는 법',
        'steps_sub': '사진 → 이미지 → 영상',
        'groups': [],
        'steps': [
            ('19-1', 'IG @tasyajijavadze', 'ChatGPT로 손바닥 위 사진 만들기', [
                '정면이고 얼굴이 또렷한 사진 1장 (혼자 나온 사진, 밝은 곳). 선글라스·모자·단체 사진·센 필터는 피하기',
                'ChatGPT에 사진을 올리고 아래 프롬프트를 그대로 붙여넣기',
                '"이 사진 속 아기와 똑같은 얼굴로 만들어줘. 눈·코·입의 위치와 비율, 턱선, 표정, 눈 크기, 볼살, 헤어라인은 바꾸지 마. 아기를 손바닥 위에 올라갈 만큼 작은 포켓사이즈로, 전신이 자연스럽게 서 있는 모습으로 만들어줘. 위에서 약 45~60도로 내려다보는 시점으로(정수리만 보이는 90도 시점은 X) 얼굴·몸·팔·다리가 다 보이게. 손바닥 전체가 보이고 아기는 손바닥 가운데에 서 있게. 배경은 흐린 실내, 스마트폰으로 찍은 것처럼 사실적인 사진으로."',
                '얼굴이 달라지면 "얼굴은 원본 그대로"를 한 번 더 강조해서 다시 생성'], 'tall'),
            ('19-2', 'IG @babychan_aibaby', '영상으로 움직이기 (이미지 → 영상)', [
                'Kling 같은 영상 AI에서 이미지→영상을 고르고 STEP 1 사진 업로드',
                '동작은 순서대로 문장으로: 예) 젖병을 물고 마시다가 활짝 웃기',
                '영어 프롬프트 예시: "Keep the exact face from the image. A palm-sized tiny baby on an open palm, macro lens, shallow depth of field, realistic shadow under the feet. A fingertip gently boops its cheek and lifts away; the baby startles, pouts, then smiles. Camera and hand stay still. Photorealistic, no text."',
                '얼굴은 말로 묘사하지 말고 사진에 맡기기 · 손과 카메라는 고정'], 'tall'),
            ('19-3', 'IG @chiho_628', '춤추게 만들기 (Kling 모션 컨트롤)', [
                'Kling → 비디오 생성 → 모션 컨트롤',
                '이미지: STEP 1에서 만든 사진 / 동작 비디오: 따라 할 춤 영상',
                "설정: 생성 파라미터 '이미지와 일치', 화질 720p, 수량 1 → 가입 때 받는 무료 크레딧 범위에서 생성",
                '춤 영상은 직접 찍었거나 허락받은 영상이 안전해요'], 'tall'),
            ('19-4', 'IG @larisa.global', '응용: 나도 미니미로', [
                '셀카 1장 + 같은 프롬프트에서 "아기"만 "사람"으로',
                '볼 콕 연출은 "boop"으로 — "pinch"라고 쓰면 볼이 늘어나요',
                '콕 → 놀람 → 손 쳐내기 → 쓰다듬기 순서로 적으면 자연스러워요'], 'tall'),
        ],
        'price_title': 'Kling 설정값',
        'price_it': 'settings',
        'price_sub': '모션 컨트롤 기준',
        'price': [('메뉴', '비디오 생성 → 모션 컨트롤'), ('이미지', 'STEP 1에서 만든 사진'), ('동작 비디오', '따라 할 춤 영상'), ('생성 파라미터', '이미지와 일치'), ('화질', '720p'), ('수량', '1')],
        'alts': [('kling', 'Kling AI', '가입 때 무료 크레딧 지급 · 720p로 무료 생성 가능', 'https://klingai.com')],
        'tips': ['3~5번은 다시 뽑을 각오로 — 처음부터 완벽하게 나오진 않아요', '720p로 먼저 테스트하고 마음에 들면 고화질로', '크기감이 무너지면 "palm-sized, macro lens, realistic shadow under the feet" 추가', '결과가 이상하면 한 번에 하나만 바꿔서 다시', "올릴 땐 인스타 'AI 정보' 라벨 켜기"],
        'notes': ['아이 사진은 가족 동의 범위 안에서만 쓰고, 다른 사람 아이 사진으로는 만들지 마세요.', 'Kling 메뉴 이름·무료 크레딧은 바뀔 수 있어요(2026년 10월 기준).', '영상 출처: IG @tasyajijavadze · @babychan_aibaby · @chiho_628 · @larisa.global'],
        'stat': ('', ''),
        'template': False,
    },
    {
        'slug': '18',
        'reel': 18,
        'type': 'guide',
        'part': 'HOW TO',
        'title': 'ChatGPT에서 Higgsfield로 영상·게임 만드는 법',
        'short': '채팅창에 슬래시(/) 명령어 한 줄',
        'lede': '9월 30일 나온 ChatGPT용 Higgsfield 확장이에요. 채팅창에 슬래시(/) 명령어만 치면 영상·광고·게임까지 만들 수 있어요. 2026년 10월 기준이에요.',
        'hero': '18-hero',
        'hero_shape': 'stack',
        'hero_tag': 'X @higgsfield_ai',
        'facts': [('/', '명령어 한 줄'), ('5+', '명령어'), ('9.30', '출시')],
        'ctas': [('명령어 보기', '#price'), ('예시 보기', '#s1')],
        'steps_title': '이렇게 써요',
        'steps_sub': '릴스에 나온 두 가지 예시',
        'groups': [],
        'steps': [
            ('18-hero', 'X @higgsfield_ai', '/genjutsu — 촬영본을 다른 장면으로', ['촬영한 영상을 올리고 /genjutsu 입력', '바꿀 것을 하나씩 적기: 그린스크린 → 절벽 계곡, 배우 → 갑옷 기사, 매트리스 → 거인 손바닥', '사물·장소·캐릭터가 바뀌고 움직임은 그대로 남아요', '위가 실제 촬영본, 아래가 AI 결과'], 'stack'),
            ('18-1', 'X @higgsfield_ai', '결과는 이렇게 나와요', ['매트리스 위에 누운 배우가 거인 손바닥 위의 기사로', '카메라 움직임과 몸짓은 촬영본 그대로', '짧게 먼저 만들어보고 마음에 들면 길게'], 'wide'),
            ('18-2', 'X @higgsfield_ai', '/games — 게임까지', ['만들고 싶은 게임을 문장으로 설명', '영상 속 사무라이 게임은 Higgsfield Games로 만든 결과', '위는 Claude Opus 5.5, 아래는 GPT-6 Astra로 만든 버전'], 'stack'),
        ],
        'price_title': '명령어',
        'price_it': 'commands',
        'price_sub': '채팅창에 / 를 치면 나와요',
        'price': [('/genjutsu', '사물·장소·캐릭터 바꾸기'), ('/effects', '바이럴 이펙트'), ('/product', '제품 광고 영상'), ('/motion', '모션그래픽'), ('/marketing-studio', '마케팅 소재'), ('그 밖에', '광고 · UGC · 웹사이트 · 게임')],
        'alts': [],
        'tips': ['ChatGPT에서 Higgsfield 확장을 추가하고 Higgsfield 계정을 연결해요', '채팅창에 / 를 치면 쓸 수 있는 명령어가 떠요', '바꿀 대상은 배경·사람·소품을 각각 구체적으로 적어요', '영상 생성은 Higgsfield 크레딧으로 계산돼요 — 짧은 테스트부터'],
        'notes': ['출시일과 명령어 목록은 Higgsfield 공식 변경 이력(2026.9.30) 기준이에요. 메뉴 이름은 ChatGPT 화면에 따라 다를 수 있어요.', 'Higgsfield는 2026년 8월 협찬 홍보 논란이 있었고, 약관상 업로드한 영상이 학습에 쓰일 수 있어요.', '영상 출처: X @higgsfield_ai'],
        'stat': ('', ''),
        'template': False,
    },
    {
        'slug': '17',
        'reel': 17,
        'type': 'guide',
        'part': 'HOW TO',
        'title': '우리 강아지도 춤추게 만드는 법',
        'short': '사진 한 장 + 댄스 영상 하나면 끝',
        'lede': '요즘 릴스에서 난리 난 강아지 댄스 영상, 만드는 법을 3단계로 정리했어요. 2026년 10월 기준이에요.',
        'hero': '17-hero',
        'hero_shape': 'tall',
        'groups': [],
        'steps': [
            ('17-1', 'IG @teddy_smile1205', '강아지 사진 고르기', ['정면에서 찍은 전신 사진', '머리나 몸이 가려지지 않게', '한 마리만 나오게', '댄스 영상과 같은 구도(전신이면 전신)']),
            ('17-2', 'IG @marimomovie', '따라 할 댄스 영상 고르기', ['카메라가 고정되고 컷이 없는 영상', '사람 전신이 다 나오는 영상', '4~30초 길이', '내가 찍은 영상이나 허락받은 영상이 안전해요']),
            ('17-3', 'X @higgsfield_ai', 'Higgsfield Genjutsu로 만들기', ['higgsfield.ai → Video → Genjutsu → Motion Transfer', '댄스 영상을 올리거나 Motion Library에서 인기 영상 remake', '이미지를 강아지 사진으로 교체', '빨간 링크를 초록으로 켜고 화질 선택 후 생성 (약 10분)']),
        ],
        'price': [('480p', '40크레딧 · 약 $2'), ('720p', '104크레딧 · 약 $5.2'), ('1080p', '144크레딧 · 약 $7.2')],
        'alts': [('kling', 'Kling Motion Control', '캐릭터 이미지 + 동작 영상(3~30초). 매일 무료 크레딧, 무료는 저화질·워터마크', 'https://klingai.com'),
                 ('viggle', 'Viggle', '하루 5개 무료(워터마크), 최대 약 15초', 'https://viggle.ai')],
        'tips': ['480p로 먼저 테스트하고, 마음에 들면 고화질로', "Motion Library 인기 영상은 'remake'로 바로 따라 만들기", '결과가 이상하면 한 번에 하나씩만 바꿔서 다시', '음악은 원래 댄스 영상 노래를 쓰면 박자가 맞아요'],
        'notes': ['Higgsfield는 2026년 8월 협찬 홍보 논란이 있었고, 약관상 업로드한 영상이 학습에 쓰일 수 있어요.', '남이 찍은 댄스 영상에는 영상 저작권과 출연자 초상권이 있어요.', '가격은 Higgsfield 공식 블로그 기준(15초 영상)이고, 요금제는 자주 바뀌어요.'],
        'stat': ('', ''),
        'template': False,
    },
    {
        'slug': '16',
        'reel': 16,
        'type': 'tools',
        'part': 'AI TOOLS',
        'title': 'AI 초보 vs 고수, 쓰는 사이트 13',
        'short': '영상·이미지·목소리부터 3D·번역까지',
        'lede': '다들 쓰는 기본 기능 말고, AI 고수들이 분야마다 따로 쓰는 사이트를 모았어요. 2026년 10월 기준이에요.',
        'hero': '16-hero',
        'hero_shape': 'wide',
        'stat': ('기준', '26.10'),
        'groups': [],
        'tools': [('영상', '챗봇 앱에서 바로 생성', 'Kling 4.0', '여러 컷 연출에 음성·립싱크까지 한 번에', 'https://klingai.com', '16-01', 'X @Kling_ai'), ('이미지', '채팅창에 "그려줘"', 'Midjourney V8.2', '내 취향을 학습해서 미감이 달라요', 'https://www.midjourney.com', '16-02', 'X @midjourney'), ('이미지 편집', '무료 업스케일 사이트', 'Magnific', '캐릭터 생성·편집·업스케일을 한 곳에서', 'https://www.magnific.com', '16-03', 'X @magnific'), ('목소리', '편집앱 기본 TTS', 'ElevenLabs v3', '[속삭임] [웃음] 태그로 감정 연기', 'https://elevenlabs.io', '16-04', 'X @ElevenLabs'), ('음악', 'Suno 기본 모드', 'Suno Studio', '악기별로 쪼개서 다시 만드는 AI 작곡실', 'https://suno.com', '16-05', 'X @jerrod_lew'), ('더빙', '자막만 번역', 'sync.', '입모양까지 그 나라 말로 바꿔줘요', 'https://sync.so', '16-06', 'X @synclabs'), ('캐릭터 광고', '기본 아바타', 'Hedra', '캐릭터 하나로 광고 캠페인까지', 'https://www.hedra.com', '16-07', 'X @hedra_labs'), ('워크플로', '사이트마다 따로 돌리기', 'Figma Weave', '여러 AI를 노드로 연결해 한 번에', 'https://www.figma.com', '16-08', 'X @figma'), ('3D', '3D는 어렵다고 포기', 'Tripo', '사진 몇 장으로 3D 모델 완성', 'https://www.tripo3d.ai', '16-09', 'X @tripoai'), ('리서치', '그냥 검색', 'Perplexity', '출처 달린 리포트를 알아서 작성', 'https://www.perplexity.ai', '16-10', 'X @perplexity_ai'), ('자료 요약', '챗봇에 PDF 던지기', 'Gemini Notebook', '내 자료 안에서만 답해요 (구 NotebookLM)', 'https://notebooklm.google.com', '16-11', 'X @Gemini_Notebook'), ('웹사이트', '템플릿 사이트', 'Framer', '프롬프트로 만들고 바로 배포', 'https://www.framer.com', '16-12', 'X @framer'), ('번역', '번역기에 복붙', 'DeepL Voice', '회의 중 실시간 음성 번역', 'https://www.deepl.com', '16-13', 'X @DeepLcom')],
        'template': False,
    },
    {
        'slug': '15',
        'reel': 15,
        'part': 'PART 2',
        'title': 'AI 영상이 진짜가 되는 프롬프트 치트키 10',
        'short': '블랙박스 원테이크부터 같은 장면 다시 찍기까지',
        'lede': '조회수 6,414만 블랙박스 영상을 포함해, 원작자들이 공개한 Seedance 2.5 프롬프트에서 핵심 문장만 뽑았어요.',
        'hero': '15-hero',
        'hero_shape': 'tall',
        'stat': ('원작 조회', '6,414만'),
        'groups': [
            {
                'who': '@techhalla',
                'what': '블랙박스 콜라·멘토스 영상',
                'tool': 'GPT Image 2.5 → Seedance 2.5',
                'url': 'https://x.com/techhalla/status/2100526482212712584',
                'shape': 'tall',
                'items': [
                    ('01', '15-01', '첫 장면을 실사 이미지로 먼저 고정', 'lock the initial frame to a realistic one',
                     '바로 영상을 만들지 말고 <b>이미지 AI로 실사 같은 첫 장면을 먼저</b> 만든 뒤, 그 사진을 영상 AI 참조로 넣어요.'),
                    ('02', '15-02', '영화 말고 블랙박스 화질로', 'lived-in dashcam JPEG, not cinema, not HDR',
                     'AI 티가 나는 가장 큰 이유는 <b>너무 깨끗한 화질</b>이에요. 영화 느낌은 not으로 막아요.'),
                    ('03', '15-03', '초 단위로 사건 배치', '16-20s: [IT GOES] WHITE FOAM COLUMN',
                     '구간마다 무슨 일이 일어나는지 적으면 <b>클라이맥스가 원하는 타이밍에</b> 터져요. 원작에선 정확히 16초에 거품 기둥이 솟아요.'),
                    ('04', '15-04', '컷 없는 원테이크', 'CONTINUOUS SINGLE TAKE the entire 30s. Digital pinch-zooms only (no cuts).',
                     '컷 대신 <b>줌만 쓰는 한 번의 촬영</b>처럼 만들면 진짜 누가 찍은 영상 같아요.'),
                    ('05', '15-05', '인물·배경을 목록으로 고정', 'LOCKED CAST: (인물 설명)\nLOCKED SET: (장소·차량·소품)',
                     '<b>"No second person"</b>처럼 나오면 안 되는 것까지 적어서 엉뚱한 사람이 끼어드는 걸 막아요.'),
                ],
            },
            {
                'who': '@Scenario_gg',
                'what': '같은 영상을 다른 각도로 다시 찍기',
                'tool': 'Seedance 2.5 영상→영상 · 위 AI / 아래 원본',
                'url': 'https://x.com/Scenario_gg/status/2102365054389899695',
                'shape': 'stack',
                'items': [
                    ('06', '15-06', '내 영상의 연기·타이밍은 그대로', 'Do not restage, re-perform, re-time or reinterpret it.',
                     '내가 찍은 영상을 @video1로 넣고 이 문장을 쓰면 <b>움직임과 말하는 타이밍은 원본 그대로</b>예요.'),
                    ('07', '15-07', '바뀌는 건 카메라뿐', 'The only variable is camera position and lens.',
                     '같은 순간을 <b>다른 자리의 카메라로 다시 찍은 것처럼</b>. 원작자는 한 테이크로 13개 앵글을 만들었어요.'),
                    ('08', '15-08', '원본과 같은 속도로', 'Real time, 1:1 with @video1. No speed ramps, added slow motion, freeze frames or time remaps.',
                     'AI가 멋대로 <b>슬로모션을 넣는 걸</b> 막아서 원본 오디오와 입 모양이 어긋나지 않아요.'),
                ],
            },
            {
                'who': '@RishuaVR',
                'what': '인도네시아 골목 브이로그',
                'tool': 'Seedance 2.5',
                'url': 'https://x.com/RishuaVR/status/2089204108175741157',
                'shape': 'wide',
                'items': [
                    ('09', '15-09', '끝까지 같은 사람으로', 'Maintain consistent identity, clothing, hairstyle, and appearance throughout the entire video.',
                     '먼저 <b>나이·옷·피부·머리 모양까지</b> 자세히 묘사하고 이 문장을 붙여요.'),
                    ('10', '15-10', '일부러 흔들리게', 'DV camcorder aesthetic. Heavy handheld shake, frequent autofocus hunting. No stabilization. No cinematic camera moves.',
                     '손떨림·초점 흔들림을 넣고 매끈한 카메라는 막아서 <b>친구가 찍어준 브이로그</b> 느낌.'),
                ],
            },
        ],
        'template': True,
    },
    {
        'slug': '14',
        'reel': 14,
        'part': 'PART 1',
        'title': 'AI 영상 고수들만 아는 프롬프트 치트키 5',
        'short': '홈비디오, 게임 화면, 초 단위 샷까지',
        'lede': '조회수 수백만 AI 영상 다섯 편의 공개 프롬프트에서, 공통으로 들어간 한 문장씩을 뽑았어요.',
        'hero': '14-hero',
        'hero_shape': 'wide',
        'stat': ('원작 북마크', '1.1만+'),
        'groups': [
            {'who': '@Sheldon056', 'what': '홈비디오', 'tool': 'Seedance 2.5', 'url': 'https://x.com/Sheldon056', 'shape': 'wide',
             'items': [('01', '14-01', '연출 없는 홈비디오처럼', 'documentary-style personal home video',
                        'spontaneous, imperfect를 같이 쓰면 <b>진짜 일상</b> 같아요.')]},
            {'who': '@_VVSVS', 'what': '게임 화면', 'tool': 'Midjourney 8.2 + Seedance 2.5', 'url': 'https://x.com/_VVSVS', 'shape': 'wide',
             'items': [('02', '14-02', '게임 화면처럼', 'gameplay capture, rigid follow camera, flat exposure, deep focus, no film grain',
                        '카메라를 <b>게임 카메라</b>로 묘사해요.')]},
            {'who': '@SyntheSarah', 'what': '4K 숲', 'tool': 'Seedance 2.5', 'url': 'https://x.com/SyntheSarah', 'shape': 'wide',
             'items': [('03', '14-03', '초 단위로 샷 나누기', '0-4s: wide shot / 4-8s: medium shot / 8-12s: close-up',
                        '한 영상 안에 <b>여러 컷이 자연스럽게</b> 이어져요.')]},
            {'who': '@laviniavelle', 'what': '구름 마을', 'tool': 'Seedance 2.5', 'url': 'https://x.com/laviniavelle', 'shape': 'wide',
             'items': [('04', '14-04', '끌어올리며 공개', 'slowly pull the camera upward and reveal',
                        '카메라가 올라가며 전체가 드러나서 <b>스케일이 커져요</b>.')]},
            {'who': '@AIwithkhan', 'what': '가면 군중', 'tool': 'Seedance 2.5', 'url': 'https://x.com/AIwithkhan', 'shape': 'wide',
             'items': [('05', '14-05', '참조 이미지로 인물 고정', 'use the uploaded images as exact visual references',
                        '참조 이미지를 정확한 기준으로 지정하면 <b>인물·의상이 안 바뀌어요</b>.')]},
        ],
        'template': False,
    },
]

TEMPLATE = """[STYLE + CAMERA]
Vertical 9:16 smartphone video. lived-in phone footage, not cinema, not HDR.
CONTINUOUS SINGLE TAKE the entire 10s. Digital pinch-zooms only (no cuts).

[LOCKED CAST]
(인물: 나이, 옷, 피부, 머리 모양까지 자세히)
Maintain consistent identity, clothing, hairstyle, and appearance throughout the entire video.

[LOCKED SET]
(장소: 배경, 소품, 날씨, 시간대)
(나오면 안 되는 것: No second person, No billboards…)

[TIMELINE]
0-3s: [HOOK] (첫 장면, 바로 눈길 끄는 사건)
3-7s: (전개)
7-10s: [IT GOES] (클라이맥스)

[AVOID]
No stabilization. No cinematic camera moves. No modern color grading."""
