"""Recipe No.20 — 직장인 AI 18가지 toolkit (type 'kit')."""

V20 = {
    'slug': '20', 'reel': 20, 'type': 'kit',
    'part': 'AI TOOLS',
    'title': '직장인 AI 18가지, 가격까지 한 장 정리',
    'short': '회의록·PPT·엑셀·조사·번역까지 업무별로',
    'lede': '직장인이 많이 쓰는 AI 18가지를 업무별로 골라, 무료로 어디까지 되는지와 월 가격을 정리했어요. 툴마다 바로 붙여 쓰는 업무용 프롬프트도 넣었어요.',
    'hero': '20-hero', 'hero_shape': 'tall', 'hero_tag': '2026.10 가격 기준',
    'asof': '26.10', 'asof_full': '2026년 10월 5일 (각 공식 가격 페이지)',
    'list_sub': '개인 요금제 · 월 결제 기준 · 누르면 자세히',
    'start_title': '어디부터 써볼까요?', 'start_it': 'where to start', 'start_sub': '돈 안 내고 시작하는 순서',
    'prep_title': '이렇게 시작하면 돈 안 들어요',
    'prep': [('1주차 · 무료로 충분한 것부터', '클로바노트(회의록) · 릴리스 AI(유튜브·PDF 요약) · Gemini Notebook(자료 질문) · Perplexity(검색)'),
             ('2주차 · 만능 AI 하나 정하기', 'ChatGPT · Claude · Gemini 무료 버전을 같은 업무로 써보고 손에 맞는 걸 하나 고르기'),
             ('3주차 · 반복 업무만 유료로', '매주 PPT를 만든다면 Gamma, 엑셀이 많다면 Excel Copilot처럼 자주 하는 일 하나만 결제'),
             ('결제 전 꼭', '월 결제 vs 연 결제 비교 (연 결제가 최대 20~28% 저렴) · 회사 보안 규정에서 외부 AI 사용 가능 여부 확인')],
    'sections': [
        {'label': '회의·녹음', 'title': '회의 끝나면 회의록이 와 있어요', 'desc': '녹음만 해두면 받아쓰기, 요약, 할 일 정리까지 해줘요. 한국어 회의는 클로바노트, 영어 회의는 Otter가 편해요.',
         'clip': '20-1', 'cred': 'Otter 공식 영상',
         'tools': [
             {'logo': 'clova', 'name': '클로바노트', 'use': '회의 녹음 → 요약·할 일', 'free': '무료 월 300분', 'good': True, 'price': '무료', 'price_note': '개인 유료 요금제 없음',
              'url': 'https://clovanote.naver.com', 'starter_label': '회의록을 보고용으로 바꾸는 프롬프트 (만능 AI에 붙여넣기)',
              'starter': '아래 회의록을 상사에게 보고할 형식으로 정리해줘.\n1. 결론 3줄\n2. 결정된 사항\n3. 할 일 표 (담당자 / 마감일 / 할 일)\n4. 아직 정해지지 않은 것\n추측해서 채우지 말고, 회의록에 없는 내용은 "확인 필요"라고 써줘.\n\n[회의록 붙여넣기]',
              'how': '앱에서 녹음 → 끝나면 AI 요약이 자동으로 생겨요. 요약 텍스트를 복사해 위 프롬프트와 함께 ChatGPT·Claude에 넣으면 보고용으로 바뀌어요.'},
             {'logo': 'otter', 'name': 'Otter', 'use': '영어 회의 실시간 기록', 'free': '무료 월 300분', 'price': '$16.99', 'price_note': '/월 (연 결제 $8.33)',
              'url': 'https://otter.ai', 'starter_label': 'Otter 채팅창에 바로 물어보기',
              'starter': 'Summarize this meeting in Korean. List decisions, action items with owners and deadlines, and open questions. Keep it under 10 lines.',
              'how': 'Zoom·Google Meet·Teams에 Otter를 연결하면 회의에 자동으로 들어와 받아써요. 회의 후 Otter 채팅에 위 문장을 넣으면 한국어 요약이 나와요.'},
             {'logo': 'plaud', 'name': 'Plaud', 'use': '폰·옷에 붙이는 AI 녹음기', 'free': '무료 월 300분', 'price': '$159~', 'price_note': '기기값 · 구독은 선택',
              'url': 'https://www.plaud.ai', 'how': '대면 미팅·통화·강의를 버튼 하나로 녹음해요. 기기값이 들어서, 녹음이 많은 영업·인터뷰 직군에게 추천해요. 무료 플랜으로 월 300분까지 받아쓰기돼요.'},
         ]},
        {'label': 'PPT·디자인', 'title': '개요만 쓰면 슬라이드가 나와요', 'desc': '빈 슬라이드부터 꾸미지 말고, 내용(개요)만 정리해서 넣으세요. 디자인은 AI가 잡고 사람은 내용을 고쳐요.',
         'clip': '20-2', 'cred': 'Gamma 공식 영상',
         'tools': [
             {'logo': 'gamma', 'name': 'Gamma', 'use': '개요 → 슬라이드 자동 생성', 'free': '무료 400크레딧', 'price': '$12', 'price_note': '/월 (연 결제 $9)',
              'url': 'https://gamma.app', 'starter_label': 'Gamma "생성" 칸에 넣는 프롬프트',
              'starter': '[주제: 2026년 하반기 마케팅 성과 보고] 사내 임원 보고용 10장 슬라이드를 만들어줘.\n구성: 1) 한 줄 결론 2) 핵심 지표 3개 3) 잘된 점 4) 아쉬운 점과 원인 5) 다음 분기 계획 6) 필요한 지원\n톤: 간결하게, 한 장에 문장 3줄 이내, 숫자는 크게.',
              'how': '무료 크레딧은 가입할 때 한 번만 줘요. 프롬프트당 최대 10장까지 만들 수 있고, PPTX·PDF로 내보내기돼요 (무료는 Gamma 로고 표시).'},
             {'logo': 'genspark', 'name': 'Genspark', 'use': '주제만 주면 조사부터 PPT까지', 'free': '하루 100크레딧', 'price': '$24.99', 'price_note': '/월 (연 결제 $19.99)',
              'url': 'https://www.genspark.ai', 'starter_label': 'AI 슬라이드에 넣는 프롬프트',
              'starter': '[주제: 국내 구독형 밀키트 시장]을 조사해서 8장짜리 발표 자료를 만들어줘. 시장 규모, 주요 업체 3곳 비교표, 소비자 트렌드, 시사점 순서로. 모든 수치에 출처를 달아줘.',
              'how': '조사가 필요한 발표에 좋아요. 자료를 찾아 읽고 슬라이드까지 만들어줘서 시간이 걸리지만, 출처를 꼭 열어 확인하세요.'},
             {'logo': 'canva', 'name': 'Canva', 'use': '포스터·카드뉴스·썸네일', 'free': '무료 AI 20회', 'price': '₩9,900', 'price_note': '/월 (연 ₩99,000)',
              'url': 'https://www.canva.com', 'starter_label': 'Canva AI에 넣는 프롬프트',
              'starter': '사내 공지용 A4 세로 포스터를 만들어줘. 제목 "10월 보안 교육 안내", 일시 10월 20일 오후 2시, 장소 본관 3층 대회의실. 깔끔한 기업 스타일, 파란색 계열, 아이콘 2~3개.',
              'how': '한국 요금은 원화(₩9,900/월)로 결제돼요. 템플릿을 고른 뒤 Magic 기능으로 문구·크기 변경을 시키면 더 빨라요.'},
         ]},
        {'label': '엑셀', 'title': '수식은 말로 시키세요', 'desc': '함수 이름을 몰라도 "이 열에서 이것만 골라서 합계"처럼 말로 설명하면 수식과 표를 만들어줘요.',
         'clip': '20-3', 'cred': 'Microsoft 공식 영상',
         'tools': [
             {'logo': 'excel', 'name': 'Excel Copilot', 'use': '엑셀 안에서 말로 분석·수식', 'free': '무료 앱은 제한적', 'price': '₩12,500', 'price_note': '/월 · M365 Personal',
              'url': 'https://www.microsoft.com/ko-kr/microsoft-365/excel', 'starter_label': 'Copilot 창에 넣는 프롬프트',
              'starter': '이 표에서 지역별·월별 매출 합계를 피벗으로 만들고, 전월 대비 증감률 열을 추가해줘. 증감률이 -10% 이하인 칸은 빨간색으로 표시해줘.',
              'how': 'M365 Personal(₩12,500/월)에 개인용 Copilot이 포함돼요. 표를 "표로 서식 지정"해 두면 Copilot이 데이터를 더 정확히 읽어요.'},
             {'logo': 'chatgpt', 'name': 'ChatGPT for Excel', 'use': '시트 안에서 바로 질문', 'free': '무료 계정도 사용', 'good': True, 'price': '$20', 'price_note': '/월 · Plus부터 넉넉',
              'url': 'https://help.openai.com/en/articles/20001063-chatgpt-for-excel-and-google-sheets', 'starter_label': '수식이 막힐 때',
              'starter': 'B열 날짜 중 이번 달에 해당하고, C열 담당자가 "김민지"인 행의 D열 금액 합계를 구하는 수식을 만들어줘. 수식이 어떻게 작동하는지 한 줄씩 설명도 해줘.',
              'how': '엑셀·구글 시트 추가 기능으로 설치해요. 무료·Go 계정도 쓸 수 있지만 사용량이 적고, Plus($20)부터 넉넉해요.'},
             {'logo': 'claude', 'name': 'Claude in Excel', 'use': '시트 전체 분석·모델링', 'free': '유료 전용 · 베타', 'price': '$20', 'price_note': '/월~ · Pro 이상',
              'url': 'https://claude.com/claude-in-excel', 'starter_label': '여러 시트를 한 번에 볼 때',
              'starter': '이 통합문서의 모든 시트를 확인해서 매출 시트와 비용 시트가 연결되는 구조를 설명해줘. 그다음 비용이 10% 오를 때 영업이익이 어떻게 바뀌는지 새 시트에 시나리오 표로 만들어줘.',
              'how': 'Pro 이상 요금제에서 쓸 수 있는 베타 기능이에요. 수식이 어디서 왔는지 셀 단위로 짚어주는 게 장점이에요.'},
         ]},
        {'label': '조사·요약', 'title': '읽기 전에 먼저 물어보세요', 'desc': '검색은 출처가 달린 답으로, 긴 PDF·영상은 요약 노트로 바꿔서 봐요. 셋 다 무료로도 충분히 쓸 수 있어요.',
         'clip': '20-4', 'cred': 'X @perplexity_ai',
         'tools': [
             {'logo': 'perplexity', 'name': 'Perplexity', 'use': '출처 달린 검색 답변', 'free': '무료 검색 무제한', 'good': True, 'price': '$20', 'price_note': '/월 (연 $200)',
              'url': 'https://www.perplexity.ai', 'starter_label': '시장 조사할 때',
              'starter': '2026년 국내 [전기자전거] 시장 규모와 주요 업체 5곳을 조사해줘. 업체별 가격대, 강점, 최근 뉴스를 표로 정리하고 모든 수치에 출처 링크를 달아줘. 확인되지 않은 내용은 "확인 불가"로 써줘.',
              'how': '답 아래 숫자를 누르면 출처 페이지로 가요. 보고서에 쓸 숫자는 꼭 출처를 열어서 확인하세요.'},
             {'logo': 'notebook', 'name': 'Gemini Notebook', 'use': '내 자료 넣고 질문 (구 NotebookLM)', 'free': '노트북 100개', 'good': True, 'price': '₩7,500', 'price_note': '/월 · AI Plus',
              'url': 'https://notebooklm.google.com', 'starter_label': '자료를 올린 뒤 질문',
              'starter': '올린 자료 안에서만 답해줘. 신입 사원이 첫날 꼭 알아야 할 내용 10가지를 정리하고, 항목마다 어느 문서 몇 쪽에 있는지 출처를 달아줘. 자료에 없는 내용은 "자료에 없음"이라고 써줘.',
              'how': '2026년 7월 NotebookLM에서 이름이 바뀌었어요. 사내 규정·매뉴얼 PDF를 넣어두면 사내 Q&A 봇처럼 쓸 수 있어요 (회사 보안 규정 먼저 확인).'},
             {'logo': 'lilys', 'name': '릴리스 AI', 'use': '유튜브·PDF·녹음 요약 노트', 'free': '요약·채팅 무제한', 'good': True, 'price': '₩7,900', 'price_note': '/월 · 스타터',
              'url': 'https://lilys.ai', 'starter_label': '요약 노트에 이어서 물어보기',
              'starter': '이 영상 내용을 우리 팀 업무에 적용할 수 있는 아이디어 5가지로 바꿔줘. 팀은 [온라인 쇼핑몰 마케팅팀]이고, 아이디어마다 바로 해볼 수 있는 첫 행동 하나씩 적어줘.',
              'how': '유튜브 링크만 붙여넣으면 타임라인별 요약 노트가 생겨요. 무료로도 요약·채팅은 횟수 제한 없이 돼요.'},
         ]},
        {'label': '번역·정리', 'title': '영문 메일과 문서 정리는 맡기세요', 'desc': '번역은 번역 전용 AI가 자연스럽고, 정리는 내가 쓰는 문서 도구 안에서 하는 게 편해요. 글을 그림으로 바꿔주는 Napkin도 보고서에 유용해요.',
         'clip': '20-5', 'cred': 'X @napkin_ai',
         'tools': [
             {'logo': 'deepl', 'name': 'DeepL', 'use': '메일·문서 번역', 'free': '무료 월 5만 자', 'price': '$10.49', 'price_note': '/월 · 한국 기준',
              'url': 'https://www.deepl.com', 'starter_label': '번역 후 톤 다듬기 (만능 AI에 붙여넣기)',
              'starter': '아래 영문 메일을 해외 거래처에 보내는 정중한 비즈니스 톤으로 다듬어줘. 요청 사항은 첫 문단에, 마감일은 굵게 표시해줘. 바꾼 부분은 마지막에 한국어로 설명해줘.\n\n[DeepL로 번역한 메일 붙여넣기]',
              'how': '문서 파일(워드·PPT·PDF)을 통째로 올리면 서식을 유지한 채 번역돼요. 무료는 월 1개 파일까지예요.'},
             {'logo': 'notion', 'name': 'Notion AI', 'use': '회의록·문서 자동 정리', 'free': '무료는 체험만', 'price': '₩36,000', 'price_note': '/월 · 비즈니스',
              'url': 'https://www.notion.com/ko/product/ai', 'starter_label': '노션 페이지에서 AI에게',
              'starter': '이 페이지의 회의 메모를 정리해서 "결정 사항 / 할 일 / 다음 회의 안건" 세 개의 토글로 나눠줘. 할 일은 담당자 이름을 앞에 붙여줘.',
              'how': 'AI 전체 기능(에이전트·AI 회의록)은 비즈니스 요금제부터예요. 팀이 이미 노션을 쓴다면, 개인 결제보다 팀 단위 도입을 먼저 확인하세요.'},
             {'logo': 'napkin', 'name': 'Napkin AI', 'use': '글 → 도식·인포그래픽', 'free': '무료 주 500크레딧', 'good': True, 'price': '$9', 'price_note': '/월 (연 $6.75)',
              'url': 'https://www.napkin.ai', 'starter_label': 'Napkin에 붙여넣는 글 예시',
              'starter': '신규 고객 온보딩은 4단계로 진행된다. 1단계 가입 후 환영 메일 발송, 2단계 3일 안에 사용법 영상 안내, 3단계 7일째 담당자 전화, 4단계 30일째 만족도 조사. 각 단계의 담당 부서는 마케팅, CS, 영업, CS 순이다.',
              'how': '글을 붙여넣고 문단 옆 번개 아이콘을 누르면 도식 후보가 여러 개 나와요. PPT·SVG로 내보내 보고서에 바로 넣을 수 있어요.'},
         ]},
        {'label': '만능 AI', 'title': '하나는 꼭 손에 익혀두세요', 'desc': '세 개 다 무료로 시작할 수 있어요. 같은 업무를 셋에 한 번씩 시켜보고, 내 일에 맞는 하나를 골라 깊게 쓰는 걸 추천해요.',
         'clip': '20-6', 'cred': 'X @OpenAI · @claudeai · @GeminiApp',
         'tools': [
             {'logo': 'chatgpt', 'name': 'ChatGPT', 'use': '글쓰기·분석·이미지까지', 'free': '무료로도 충분', 'good': True, 'price': '$8', 'price_note': '/월 Go · Plus $20',
              'url': 'https://chatgpt.com', 'starter_label': '보고서 초안',
              'starter': '[주제]에 대한 1쪽짜리 내부 보고서 초안을 써줘. 구성은 배경 → 현황(숫자 3개) → 문제점 → 제안 → 기대 효과. 내가 모르는 숫자는 [ ]로 비워두고, 마지막에 내가 채워야 할 항목을 목록으로 알려줘.'},
             {'logo': 'claude', 'name': 'Claude', 'use': '긴 문서·보고서 작성', 'free': '무료로도 충분', 'good': True, 'price': '$20', 'price_note': '/월 Pro (연 $17)',
              'url': 'https://claude.ai', 'starter_label': '긴 문서 검토',
              'starter': '첨부한 계약서(또는 기획서)를 읽고, 우리 회사 입장에서 불리하거나 애매한 문장 5개를 찾아줘. 문장마다 원문 인용, 왜 문제인지, 고친 문장 제안 순서로 써줘. 법률 자문이 아니라 검토 메모로만 써줘.'},
             {'logo': 'gemini', 'name': 'Gemini', 'use': 'Gmail·구글 문서 연동', 'free': '무료로도 충분', 'good': True, 'price': '₩7,500', 'price_note': '/월 AI Plus · Pro ₩29,000',
              'url': 'https://gemini.google.com', 'starter_label': '메일함 정리',
              'starter': '내 Gmail에서 이번 주에 받은 메일 중 답장이 필요한 것만 골라서, 보낸 사람 / 요청 내용 / 답장 기한을 표로 정리해줘. 급한 순서대로.'},
         ]},
    ],
    'faq': [('무료만으로도 충분할까요?', '회의록(클로바노트), 요약(릴리스 AI·Gemini Notebook), 검색(Perplexity)은 무료로도 일상 업무에 충분해요. PPT·엑셀처럼 매주 반복하는 일이 생기면 그때 하나만 결제하세요.'),
            ('회사 자료를 넣어도 되나요?', '회사마다 규정이 달라요. 고객 개인정보, 계약서, 미공개 실적은 넣기 전에 보안 담당자에게 확인하세요. 회사가 계약한 기업용 요금제(Team·Business)는 보통 학습에 쓰지 않는다는 조건이 붙어요.'),
            ('달러 요금은 실제로 얼마 나와요?', '카드사 환율과 해외 결제 수수료, 부가세가 붙어서 표시 가격보다 조금 더 나와요. 원화로 표시된 Canva·M365·Gemini·노션·릴리스는 원화 그대로 결제돼요.'),
            ('ChatGPT, Claude, Gemini 중 뭘 써야 해요?', '정답은 없어요. 같은 업무(예: 보고서 초안)를 셋 무료 버전에 똑같이 시켜보고, 결과가 내 스타일에 맞는 걸 고르세요.'),
            ('가격이 바뀌면요?', '이 페이지는 가격이 바뀌면 업데이트해요. 위 "가격 확인" 날짜를 보고, 결제 전엔 각 공식 사이트에서 한 번 더 확인하세요.')],
    'tips': ['프롬프트에 "모르는 건 [ ]로 비워두고 알려줘"를 붙이면 AI가 숫자를 지어내는 걸 막을 수 있어요.',
             '결과 형식(표, 3줄, 토글)을 먼저 정해주면 고칠 일이 확 줄어요.',
             '같은 일을 매주 한다면 프롬프트를 메모장에 저장해 두고 [ ] 부분만 바꿔 쓰세요.',
             '유료 결제는 한 번에 하나만. 한 달 써보고 시간이 줄었는지 확인한 뒤 다음 걸 고르세요.'],
    'glossary': [('크레딧', 'AI 기능을 쓸 때마다 차감되는 사용권. 다 쓰면 다음 달(또는 다음 날)까지 기다리거나 충전해야 해요'),
                 ('월 결제 / 연 결제', '매달 내는 가격 / 1년치를 한 번에 내는 가격. 연 결제가 보통 15~28% 싸요'),
                 ('추가 기능(애드인)', '엑셀·워드 같은 프로그램 안에 설치해서 쓰는 확장 기능'),
                 ('피벗', '긴 표를 기준별(지역별·월별)로 묶어 합계를 보여주는 엑셀 기능')],
    'notes': ['가격은 2026년 10월 5일 각 공식 가격 페이지 기준(개인 요금제·월 결제)이에요. Genspark는 공식 도움말, 클로바노트 무료 범위는 서비스 안내 기준이에요.',
              '부가세·환율·프로모션·국가에 따라 실제 결제 금액은 달라질 수 있어요.',
              '영상은 Otter·Gamma·Microsoft 공식 사이트와 X @perplexity_ai, @napkin_ai, @OpenAI, @claudeai, @GeminiApp 공식 영상이에요.'],
}
