# 미리봄 레시피 사이트 데이터. 새 릴스가 나오면 VOLUMES 맨 앞에 하나 추가하고 build.py 실행.

VOLUMES = [
    {
        'slug': '19',
        'reel': 19,
        'type': 'guide',
        'part': 'HOW TO',
        'title': '손바닥 위 포켓베이비 만드는 법',
        'short': '사진 한 장 + ChatGPT + Kling',
        'lede': '조회수 수백만이 나오는 손바닥 위 아기 영상, 사진 한 장으로 만드는 법을 프롬프트까지 그대로 정리했어요. 2026년 10월 기준이에요.',
        'hero': '19-hero',
        'hero_shape': 'tall',
        'hero_tag': 'IG @tasyajijavadze',
        'facts': [('1장', '사진'), ('3', '단계'), ('무료', '720p 가능')],
        'ctas': [('만드는 법 보기', '#s1'), ('Kling 설정값', '#price')],
        'steps_title': '만드는 법',
        'steps_sub': '사진 → 이미지 → 영상',
        'groups': [],
        'steps': [
            ('19-1', 'IG @tasyajijavadze', 'ChatGPT로 손바닥 위 사진 만들기', [
                '정면이고 얼굴이 또렷한 사진 1장 (혼자 나온 사진, 밝은 곳). 선글라스·모자·단체 사진·센 필터는 피하기',
                'ChatGPT에 사진을 올리고 아래 프롬프트를 그대로 붙여넣기',
                '"이 사진 속 아기와 똑같은 얼굴로 만들어줘. 눈·코·입의 위치와 비율, 턱선, 표정, 눈 크기, 볼살, 헤어라인은 바꾸지 마. 아기를 손바닥 위에 올라갈 만큼 작은 포켓사이즈로, 전신이 자연스럽게 서 있는 모습으로 만들어줘. 위에서 약 45~60도로 내려다보는 시점으로(정수리만 보이는 90도 시점은 X) 얼굴·몸·팔·다리가 다 보이게. 손바닥 전체가 보이고 아기는 손바닥 가운데에 서 있게. 배경은 흐린 실내, 스마트폰으로 찍은 것처럼 사실적인 사진으로."',
                '얼굴이 달라지면 "얼굴은 원본 그대로"를 한 번 더 강조해서 다시 생성'], 'tall'),
            ('19-2', 'IG @babychan_aibaby', '영상으로 움직이기 (이미지 → 영상)', [
                'Kling 같은 영상 AI에서 이미지→영상을 고르고 STEP 1 사진 업로드',
                '동작은 순서대로 문장으로: 예) 젖병을 물고 마시다가 활짝 웃기',
                '영어 프롬프트 예시: "Keep the exact face from the image. A palm-sized tiny baby on an open palm, macro lens, shallow depth of field, realistic shadow under the feet. A fingertip gently boops its cheek and lifts away; the baby startles, pouts, then smiles. Camera and hand stay still. Photorealistic, no text."',
                '얼굴은 말로 묘사하지 말고 사진에 맡기기 · 손과 카메라는 고정'], 'tall'),
            ('19-3', 'IG @chiho_628', '춤추게 만들기 (Kling 모션 컨트롤)', [
                'Kling → 비디오 생성 → 모션 컨트롤',
                '이미지: STEP 1에서 만든 사진 / 동작 비디오: 따라 할 춤 영상',
                "설정: 생성 파라미터 '이미지와 일치', 화질 720p, 수량 1 → 가입 때 받는 무료 크레딧 범위에서 생성",
                '춤 영상은 직접 찍었거나 허락받은 영상이 안전해요'], 'tall'),
            ('19-4', 'IG @larisa.global', '응용: 나도 미니미로', [
                '셀카 1장 + 같은 프롬프트에서 "아기"만 "사람"으로',
                '볼 콕 연출은 "boop"으로 — "pinch"라고 쓰면 볼이 늘어나요',
                '콕 → 놀람 → 손 쳐내기 → 쓰다듬기 순서로 적으면 자연스러워요'], 'tall'),
        ],
        'price_title': 'Kling 설정값',
        'price_it': 'settings',
        'price_sub': '모션 컨트롤 기준',
        'price': [('메뉴', '비디오 생성 → 모션 컨트롤'), ('이미지', 'STEP 1에서 만든 사진'), ('동작 비디오', '따라 할 춤 영상'), ('생성 파라미터', '이미지와 일치'), ('화질', '720p'), ('수량', '1')],
        'alts': [('kling', 'Kling AI', '가입 때 무료 크레딧 지급 · 720p로 무료 생성 가능', 'https://klingai.com')],
        'tips': ['3~5번은 다시 뽑을 각오로 — 처음부터 완벽하게 나오진 않아요', '720p로 먼저 테스트하고 마음에 들면 고화질로', '크기감이 무너지면 "palm-sized, macro lens, realistic shadow under the feet" 추가', '결과가 이상하면 한 번에 하나만 바꿔서 다시', "올릴 땐 인스타 'AI 정보' 라벨 켜기"],
        'notes': ['아이 사진은 가족 동의 범위 안에서만 쓰고, 다른 사람 아이 사진으로는 만들지 마세요.', 'Kling 메뉴 이름·무료 크레딧은 바뀔 수 있어요(2026년 10월 기준).', '영상 출처: IG @tasyajijavadze · @babychan_aibaby · @chiho_628 · @larisa.global'],
        'stat': ('', ''),
        'template': False,
    },
    {
        'slug': '18',
        'reel': 18,
        'type': 'guide',
        'part': 'HOW TO',
        'title': 'ChatGPT에서 Higgsfield로 영상·게임 만드는 법',
        'short': '채팅창에 슬래시(/) 명령어 한 줄',
        'lede': '9월 30일 나온 ChatGPT용 Higgsfield 확장이에요. 채팅창에 슬래시(/) 명령어만 치면 영상·광고·게임까지 만들 수 있어요. 2026년 10월 기준이에요.',
        'hero': '18-hero',
        'hero_shape': 'stack',
        'hero_tag': 'X @higgsfield_ai',
        'facts': [('/', '명령어 한 줄'), ('5+', '명령어'), ('9.30', '출시')],
        'ctas': [('명령어 보기', '#price'), ('예시 보기', '#s1')],
        'steps_title': '이렇게 써요',
        'steps_sub': '릴스에 나온 두 가지 예시',
        'groups': [],
        'steps': [
            ('18-hero', 'X @higgsfield_ai', '/genjutsu — 촬영본을 다른 장면으로', ['촬영한 영상을 올리고 /genjutsu 입력', '바꿀 것을 하나씩 적기: 그린스크린 → 절벽 계곡, 배우 → 갑옷 기사, 매트리스 → 거인 손바닥', '사물·장소·캐릭터가 바뀌고 움직임은 그대로 남아요', '위가 실제 촬영본, 아래가 AI 결과'], 'stack'),
            ('18-1', 'X @higgsfield_ai', '결과는 이렇게 나와요', ['매트리스 위에 누운 배우가 거인 손바닥 위의 기사로', '카메라 움직임과 몸짓은 촬영본 그대로', '짧게 먼저 만들어보고 마음에 들면 길게'], 'wide'),
            ('18-2', 'X @higgsfield_ai', '/games — 게임까지', ['만들고 싶은 게임을 문장으로 설명', '영상 속 사무라이 게임은 Higgsfield Games로 만든 결과', '위는 Claude Opus 5.5, 아래는 GPT-6 Astra로 만든 버전'], 'stack'),
        ],
        'price_title': '명령어',
        'price_it': 'commands',
        'price_sub': '채팅창에 / 를 치면 나와요',
        'price': [('/genjutsu', '사물·장소·캐릭터 바꾸기'), ('/effects', '바이럴 이펙트'), ('/product', '제품 광고 영상'), ('/motion', '모션그래픽'), ('/marketing-studio', '마케팅 소재'), ('그 밖에', '광고 · UGC · 웹사이트 · 게임')],
        'alts': [],
        'tips': ['ChatGPT에서 Higgsfield 확장을 추가하고 Higgsfield 계정을 연결해요', '채팅창에 / 를 치면 쓸 수 있는 명령어가 떠요', '바꿀 대상은 배경·사람·소품을 각각 구체적으로 적어요', '영상 생성은 Higgsfield 크레딧으로 계산돼요 — 짧은 테스트부터'],
        'notes': ['출시일과 명령어 목록은 Higgsfield 공식 변경 이력(2026.9.30) 기준이에요. 메뉴 이름은 ChatGPT 화면에 따라 다를 수 있어요.', 'Higgsfield는 2026년 8월 협찬 홍보 논란이 있었고, 약관상 업로드한 영상이 학습에 쓰일 수 있어요.', '영상 출처: X @higgsfield_ai'],
        'stat': ('', ''),
        'template': False,
    },
    {
        'slug': '17',
        'reel': 17,
        'type': 'guide',
        'part': 'HOW TO',
        'title': '우리 강아지도 춤추게 만드는 법',
        'short': '사진 한 장 + 댄스 영상 하나면 끝',
        'lede': '요즘 릴스에서 난리 난 강아지 댄스 영상, AI를 처음 써보는 분도 따라 할 수 있게 사진 고르기부터 버튼 위치·프롬프트·실패했을 때 고치는 법까지 전부 정리했어요. 2026년 10월 기준이에요.',
        'hero': '17-hero',
        'hero_shape': 'tall',
        'hero_tag': 'IG @teddy_smile1205',
        'facts': [('2개', '사진 + 춤 영상'), ('15분', '첫 결과까지'), ('무료', '크레딧으로 시작')],
        'ctas': [('처음이에요 (준비물)', '#start'), ('바로 만들기', '#s1')],
        'flow': [('강아지 사진 1장', '누구 몸으로 춤출지'), ('따라 할 춤 영상 1개', '어떤 동작을 할지'), ('AI가 동작만 옮겨요', '모션 컨트롤 · 모션 트랜스퍼'), ('우리 강아지 댄스 완성', '음악 붙여서 업로드')],
        'flow_sum': '사람이 춤추는 영상에서 "움직임"만 뽑아서, 사진 속 강아지에게 그대로 입히는 원리예요. 그래서 사진과 영상만 잘 고르면 결과의 80%가 정해져요.',
        'prep': [
            ('강아지 사진 1장', '머리부터 발끝까지 다 나온 밝은 사진. 폰 사진이면 충분해요'),
            ('따라 할 춤 영상 1개', '한 명이 전신으로 나오고 카메라가 고정된 4~30초 영상'),
            ('AI 사이트 계정 1개', 'Kling(무료 크레딧으로 시작, 추천) 또는 Higgsfield(유료, 릴스 원본 방식). 구글 계정으로 바로 가입돼요'),
            ('ChatGPT (선택)', '강아지를 두 발로 선 사진으로 바꿔주면 성공률이 확 올라가요'),
            ('시간 15~30분', '생성 대기 5~10분 포함. 2~3번은 다시 뽑는다고 생각하면 마음 편해요'),
        ],
        'routes_sub': '처음이면 A부터 — 무료로 연습하고, 마음에 들면 고화질로',
        'routes': [
            {'tag': '추천 · A', 'name': 'Kling 모션 컨트롤', 'who': '처음 해보는 분, 무료로 먼저 해보고 싶은 분', 'rec': True, 'go': '#s4', 'go_label': 'A 방법 보기',
             'rows': [('비용', '무료 크레딧으로 시작'), ('영상 길이', '3~30초'), ('난이도', '쉬움 · 버튼 5번'), ('결과', '무료는 워터마크')]},
            {'tag': 'B', 'name': 'Higgsfield Genjutsu', 'who': '릴스에 나온 그 방식 그대로, 고화질로 뽑고 싶은 분', 'go': '#s5', 'go_label': 'B 방법 보기',
             'rows': [('비용', '15초 약 $2(480p)~$7.2(1080p)'), ('영상 길이', '4~30초'), ('난이도', '보통'), ('결과', '최대 1080p')]},
            {'tag': '가장 쉬움 · C', 'name': '춤 영상 없이 프롬프트만', 'who': '춤 영상 고르기가 귀찮을 때, 5초짜리 짧은 춤', 'go': '#easy', 'go_label': 'C 방법 보기',
             'rows': [('비용', '무료 크레딧'), ('영상 길이', '5~10초'), ('난이도', '가장 쉬움'), ('결과', '간단한 리듬 타기')]},
        ],
        'steps_title': '만드는 법',
        'steps_sub': '사진 → 영상 → 생성 → 업로드',
        'steps': [
            ('17-1', 'IG @teddy_smile1205', '강아지 사진 고르기', [
                '결과의 절반은 사진이 정해요. 아래 조건을 체크하고 골라주세요',
                ('good', '이런 사진이 좋아요', ['머리부터 발끝까지 전부 나온 전신 사진', '정면 또는 살짝 옆에서, 강아지 눈높이로 찍은 사진', '밝은 곳에서 찍어 털 색이 또렷한 사진', '한 마리만 나오고, 배경이 단순한 사진']),
                ('bad', '이런 사진은 피하세요', ['얼굴만 크게 나온 클로즈업', '누워 있거나 웅크린 자세', '옷·이불·사람 손에 몸이 가려진 사진', '흔들린 사진, 여러 마리가 같이 나온 사진']),
                ('tip', '사진을 세로(9:16)로 잘라두면 세로 춤 영상과 비율이 맞아서 몸이 덜 찌그러져요'),
            ]),
            (None, '', 'ChatGPT로 "두 발로 선 강아지" 사진 만들기', [
                'AI는 사람의 팔다리 움직임을 옮겨요. 강아지가 네 발로 서 있으면 어디가 팔이고 다리인지 헷갈려서 몸이 꼬이기 쉬워요. 미리 두 발로 선 사진을 만들어 두면 성공률이 확 올라가요',
                ('do', ['chatgpt.com 접속 → 새 채팅', '입력창 왼쪽 + 버튼 → STEP 1 강아지 사진 올리기', '아래 프롬프트를 복사해서 붙여넣고 보내기', '1~2분 뒤 나온 사진을 길게 눌러(또는 우클릭) 저장']),
                ('prompt', '두 발로 선 강아지 만들기 (한국어)', '첨부한 사진 속 강아지와 똑같은 강아지로 새 사진을 만들어줘. 털 색, 무늬, 얼굴 생김새, 눈 모양, 귀 모양은 절대 바꾸지 마. 강아지가 사람처럼 뒷다리로 똑바로 서 있고, 앞발은 몸 양옆에 자연스럽게 내린 전신 모습으로. 머리부터 발끝까지 전부 보이게 위아래 여백을 넉넉히 두고, 카메라는 정면 눈높이. 배경은 밝고 단순한 실내 연습실, 9:16 세로 사진, 폰으로 찍은 것처럼 사실적으로. 옷이나 소품은 넣지 마.'),
                ('prompt', '같은 내용 (영어, 결과가 다를 때)', 'Create a new photo of the exact same dog from the attached image. Do not change its fur color, markings, face, eyes or ear shape. The dog stands upright on its hind legs like a person, front paws relaxed at its sides, full body visible from head to toe with generous space above and below. Front view at eye level. Simple bright dance-studio background, vertical 9:16, realistic smartphone photo. No clothes or props.'),
                ('tip', '옷을 입히고 싶으면 마지막 문장을 "후드티와 운동화를 입혀줘"처럼 바꾸면 돼요. 단, 털 색·얼굴이 달라지면 "얼굴과 털은 원본 그대로"를 한 번 더 써서 다시 만들어요'),
            ], None, '선택 · 추천'),
            ('17-2', 'IG @marimomovie', '따라 할 춤 영상 고르기', [
                ('good', '이런 영상이 잘 돼요', ['춤추는 사람이 딱 한 명', '머리부터 발끝까지 영상 내내 다 보임', '카메라가 고정돼 있고 중간에 컷이 없음', '배경이 단순하고 밝음, 동작이 너무 빠르지 않음', '길이 4~30초 (짧을수록 크레딧 절약)']),
                ('bad', '이런 영상은 실패가 많아요', ['여러 명이 같이 추는 영상', '카메라가 움직이거나 확대·축소되는 영상', '바닥을 구르거나 점프·회전이 아주 빠른 동작', '몸이 화면 밖으로 잘리는 영상']),
                ('do', ['내가 직접 찍기 (가장 안전, 거실에서 폰 세워두고 촬영)', '또는 Kling·Higgsfield 안의 기본 춤(Motion Library)에서 고르기', '필요한 부분만 폰 기본 편집으로 앞뒤를 잘라 4~30초로 맞추기']),
                ('warn', '남이 찍은 댄스 영상에는 영상 저작권과 출연자 초상권이 있어요. 직접 찍었거나 허락받은 영상, 사이트 기본 영상을 쓰세요'),
            ]),
            (None, '', 'A. Kling 모션 컨트롤로 만들기', [
                ('do', ['klingai.com 접속 → 오른쪽 위 로그인(구글 계정 가능)', '왼쪽 메뉴 비디오 생성(Video) → 위쪽 탭 모션 컨트롤(Motion Control)', '동작 비디오 칸에 STEP 3 춤 영상 올리기', '이미지 칸에 STEP 2 사진(없으면 STEP 1 사진) 올리기', "캐릭터 방향을 '비디오와 일치'로 두기 (춤을 그대로 따라 해요)", '화질은 표준(720p)으로 먼저 → 생성 버튼', '5~10분 뒤 결과 오른쪽 위 다운로드']),
                '프롬프트 칸은 비워도 돼요. 쓸 거라면 "동작"이 아니라 "장면"을 설명해야 해요 (동작은 영상이 정해요)',
                ('prompt', '장면 프롬프트 (선택, 그대로 복사)', 'The same dog from the image, keeping its exact face, fur color and markings. Realistic fluffy fur, bright dance studio with wooden floor, soft natural light, stable camera, high detail.'),
                ('tip', "강아지가 영상 속 사람처럼 뒤로 돌거나 몸이 비틀리면 '이미지와 일치'로 바꿔서 다시 (대신 최대 10초)"),
                ('tip', '무료 결과에는 워터마크가 있어요. 마음에 들면 그때 유료로 고화질·워터마크 없이 다시 뽑기'),
            ], None, '방법 A · 추천'),
            ('17-3', 'X @higgsfield_ai', 'B. Higgsfield Genjutsu로 만들기', [
                ('do', ['higgsfield.ai 접속 → 로그인', '위쪽 메뉴 Video → 모델 목록에서 Genjutsu → Motion Transfer', '춤 영상 올리기 (4~30초, 30초 넘으면 잘려요) 또는 Motion Library 인기 영상에서 remake', '이미지 칸을 강아지 사진으로 교체', '사진과 영상 속 사람 사이의 빨간 연결 아이콘을 눌러 초록으로 켜기', '480p로 먼저 → 생성 버튼에 표시된 크레딧 확인 후 생성 (약 10분)']),
                '프롬프트는 안 써도 돼요. 쓰려면 위 A 방법의 장면 프롬프트를 그대로 붙여넣으면 돼요',
                ('warn', '무료 플랜 결과에는 워터마크가 붙고, 다시 뽑을 때마다 크레딧이 나가요. 실패한 생성은 보통 자동 환불되지만 보장은 아니에요'),
            ], 'stack', '방법 B'),
            (None, '', '음악 붙이고 올리기', [
                ('do', ['결과에 소리가 없으면 CapCut(무료 편집 앱)에 결과 영상을 넣기', '원래 춤 영상의 소리를 아래에 깔고 시작점을 맞추기 → 박자가 딱 맞아요', '9:16 세로로 내보내기']),
                ('tip', "인스타에 올릴 때 고급 설정에서 'AI 정보' 라벨을 켜두세요"),
            ], None, '마무리'),
        ],
        'easy': {
            'title': 'C. 춤 영상 없이 프롬프트만으로',
            'sub': '사진 1장 + 문장 하나 · 5~10초짜리 리듬 타기',
            'pts': ['Kling → 비디오 생성 → 이미지에서 비디오(Image to Video) 탭', '시작 프레임에 강아지 사진(STEP 2 사진이면 더 좋아요) 올리기', '아래 프롬프트를 붙여넣고 5초 · 9:16 으로 생성', '복잡한 안무 대신 "흔들기·발 흔들기" 정도의 쉬운 동작을 써야 몸이 안 무너져요'],
            'prompts': [
                ('강아지 리듬 타기 (영어)', 'The dog from the image stands up on its hind legs and dances happily to the beat: bobbing and swaying side to side, front paws waving, tail wagging, head bopping. Same dog, same face and fur color. Camera stays still, bright room, realistic.'),
                ('같은 내용 (한국어)', '사진 속 강아지가 뒷다리로 서서 신나게 춤춰요. 박자에 맞춰 좌우로 몸을 흔들고, 앞발을 흔들고, 꼬리를 흔들고, 고개를 까딱여요. 같은 강아지, 같은 얼굴과 털 색. 카메라는 고정, 밝은 방, 실제 영상처럼.'),
            ],
        },
        'price_title': '가격',
        'price_it': 'price',
        'price_sub': '15초 영상 1개 기준 · 요금은 자주 바뀌어요',
        'price': [('Kling 모션 컨트롤', '무료 크레딧으로 시작 · 유료는 초당 크레딧'), ('Higgsfield 480p', '40크레딧 · 약 $2'), ('Higgsfield 720p', '104크레딧 · 약 $5.2'), ('Higgsfield 1080p', '144크레딧 · 약 $7.2')],
        'alts': [('kling', 'Kling AI', '모션 컨트롤 · 무료 크레딧으로 시작 (무료는 워터마크)', 'https://klingai.com'),
                 ('viggle', 'Viggle', '하루 5개 무료(워터마크) · 최대 약 15초', 'https://viggle.ai')],
        'faq': [
            ('강아지 얼굴이나 털 색이 바뀌어요', '사진이 어둡거나 작으면 AI가 얼굴을 지어내요. 밝은 정면 전신 사진으로 바꾸고, STEP 2처럼 두 발로 선 사진을 먼저 만든 뒤 넣어보세요. Kling이면 장면 프롬프트에 "same face, fur color and markings"를 넣어요.'),
            ('몸이 꼬이거나 다리가 녹아내려요', '네 발 사진 + 빠른 춤 조합에서 자주 생겨요. ① 두 발로 선 사진(STEP 2) ② 더 느린 춤 영상 ③ 머리·발이 화면에 잘리지 않게 여백 — 셋 중 하나만 바꿔서 다시 해보세요.'),
            ('강아지가 영상 속 사람처럼 뒤로 돌아버려요', "Kling에서 캐릭터 방향을 '이미지와 일치'로 바꾸면 사진 속 방향을 유지해요. 대신 최대 10초까지만 돼요."),
            ('결과가 몇 초만 나오거나 중간에 멈춰요', '컷이 있거나 카메라가 움직이는 영상, 너무 빠르고 복잡한 동작이면 짧게 끊겨요. 카메라 고정·한 명·전신 영상으로 바꿔보세요.'),
            ('생성 실패가 떠요', '영상에 사람이 여러 명이거나 얼굴·머리가 안 보이면 동작을 못 읽어요. 사진 속 강아지가 너무 작아도(화면의 5% 미만) 실패해요. 강아지가 크게 나온 사진으로 바꿔주세요.'),
            ('워터마크를 없애고 싶어요', '무료 플랜은 워터마크가 붙어요. 무료로 충분히 연습한 뒤, 제일 마음에 드는 조합만 유료로 한 번 다시 뽑는 게 제일 저렴해요.'),
        ],
        'glossary': [
            ('모션 컨트롤 / 모션 트랜스퍼', '영상 속 사람의 움직임을 사진 속 캐릭터에게 그대로 옮겨주는 기능. Kling은 모션 컨트롤, Higgsfield는 Motion Transfer라고 불러요'),
            ('레퍼런스 영상 (동작 비디오)', '"이 동작을 따라 해" 하고 보여주는 원본 춤 영상'),
            ('크레딧', 'AI 사이트 안에서 쓰는 포인트. 영상을 만들 때마다 길이·화질만큼 차감돼요'),
            ('480p · 720p · 1080p', '화질. 숫자가 클수록 선명하고 크레딧이 더 들어요. 연습은 낮게, 완성본만 높게'),
            ('이미지와 일치 · 비디오와 일치', 'Kling 설정. 비디오와 일치는 영상 속 방향·동작을 그대로, 이미지와 일치는 사진 속 방향을 유지해요'),
            ('워터마크', '결과 영상 구석에 찍히는 사이트 로고. 무료 플랜에 붙어요'),
        ],
        'tips': ['연습은 무료·저화질로, 완성본만 고화질로 — 크레딧이 제일 덜 들어요', '처음부터 완벽하게 안 나와요. 2~3번은 다시 뽑는다고 생각하기', '결과가 이상하면 사진·영상·설정 중 한 번에 하나만 바꿔서 다시', '음악은 원래 춤 영상 노래를 쓰면 박자가 맞아요', "Higgsfield는 Motion Library 인기 영상을 'remake'로 바로 따라 만들 수 있어요"],
        'notes': ['Higgsfield는 2026년 8월 협찬 홍보 논란이 있었고, 약관상 업로드한 영상이 학습에 쓰일 수 있어요.',
                  '남이 찍은 댄스 영상에는 영상 저작권과 출연자 초상권이 있어요.',
                  'Higgsfield 가격은 공식 블로그(15초 영상) 기준, Kling 메뉴 이름·무료 크레딧은 2026년 10월 기준이며 자주 바뀌어요.',
                  '영상 출처: IG @teddy_smile1205 · @marimomovie · X @higgsfield_ai'],
        'groups': [],
        'stat': ('', ''),
        'template': False,
    },
    {
        'slug': '16',
        'reel': 16,
        'type': 'tools',
        'part': 'AI TOOLS',
        'title': 'AI 초보 vs 고수, 쓰는 사이트 13개',
        'short': '영상·이미지·목소리부터 3D·번역까지',
        'lede': '다들 쓰는 기본 기능 말고, AI 고수들이 분야마다 따로 쓰는 사이트를 모았어요. 2026년 10월 기준이에요.',
        'hero': '16-hero',
        'hero_shape': 'wide',
        'stat': ('기준', '26.10'),
        'groups': [],
        'tools': [('영상', '챗봇 앱에서 바로 생성', 'Kling 4.0', '여러 컷 연출에 음성·립싱크까지 한 번에', 'https://klingai.com', '16-01', 'X @Kling_ai'), ('이미지', '채팅창에 "그려줘"', 'Midjourney V8.2', '내 취향을 학습해서 미감이 달라요', 'https://www.midjourney.com', '16-02', 'X @midjourney'), ('이미지 편집', '무료 업스케일 사이트', 'Magnific', '캐릭터 생성·편집·업스케일을 한 곳에서', 'https://www.magnific.com', '16-03', 'X @magnific'), ('목소리', '편집앱 기본 TTS', 'ElevenLabs v3', '[속삭임] [웃음] 태그로 감정 연기', 'https://elevenlabs.io', '16-04', 'X @ElevenLabs'), ('음악', 'Suno 기본 모드', 'Suno Studio', '악기별로 쪼개서 다시 만드는 AI 작곡실', 'https://suno.com', '16-05', 'X @jerrod_lew'), ('더빙', '자막만 번역', 'sync.', '입모양까지 그 나라 말로 바꿔줘요', 'https://sync.so', '16-06', 'X @synclabs'), ('캐릭터 광고', '기본 아바타', 'Hedra', '캐릭터 하나로 광고 캠페인까지', 'https://www.hedra.com', '16-07', 'X @hedra_labs'), ('워크플로', '사이트마다 따로 돌리기', 'Figma Weave', '여러 AI를 노드로 연결해 한 번에', 'https://www.figma.com', '16-08', 'X @figma'), ('3D', '3D는 어렵다고 포기', 'Tripo', '사진 몇 장으로 3D 모델 완성', 'https://www.tripo3d.ai', '16-09', 'X @tripoai'), ('리서치', '그냥 검색', 'Perplexity', '출처 달린 리포트를 알아서 작성', 'https://www.perplexity.ai', '16-10', 'X @perplexity_ai'), ('자료 요약', '챗봇에 PDF 던지기', 'Gemini Notebook', '내 자료 안에서만 답해요 (구 NotebookLM)', 'https://notebooklm.google.com', '16-11', 'X @Gemini_Notebook'), ('웹사이트', '템플릿 사이트', 'Framer', '프롬프트로 만들고 바로 배포', 'https://www.framer.com', '16-12', 'X @framer'), ('번역', '번역기에 복붙', 'DeepL Voice', '회의 중 실시간 음성 번역', 'https://www.deepl.com', '16-13', 'X @DeepLcom')],
        'template': False,
    },
    {
        'slug': '15',
        'reel': 15,
        'part': 'PART 2',
        'title': 'AI 영상이 진짜가 되는 프롬프트 치트키 10가지',
        'short': '블랙박스 원테이크부터 같은 장면 다시 찍기까지',
        'lede': '조회수 6,414만 블랙박스 영상을 포함해, 원작자들이 공개한 Seedance 2.5 프롬프트에서 핵심 문장만 뽑았어요.',
        'hero': '15-hero',
        'hero_shape': 'tall',
        'stat': ('원작 조회', '6,414만'),
        'groups': [
            {
                'who': '@techhalla',
                'what': '블랙박스 콜라·멘토스 영상',
                'tool': 'GPT Image 2.5 → Seedance 2.5',
                'url': 'https://x.com/techhalla/status/2100526482212712584',
                'shape': 'tall',
                'items': [
                    ('01', '15-01', '첫 장면을 실사 이미지로 먼저 고정', 'lock the initial frame to a realistic one',
                     '바로 영상을 만들지 말고 <b>이미지 AI로 실사 같은 첫 장면을 먼저</b> 만든 뒤, 그 사진을 영상 AI 참조로 넣어요.'),
                    ('02', '15-02', '영화 말고 블랙박스 화질로', 'lived-in dashcam JPEG, not cinema, not HDR',
                     'AI 티가 나는 가장 큰 이유는 <b>너무 깨끗한 화질</b>이에요. 영화 느낌은 not으로 막아요.'),
                    ('03', '15-03', '초 단위로 사건 배치', '16-20s: [IT GOES] WHITE FOAM COLUMN',
                     '구간마다 무슨 일이 일어나는지 적으면 <b>클라이맥스가 원하는 타이밍에</b> 터져요. 원작에선 정확히 16초에 거품 기둥이 솟아요.'),
                    ('04', '15-04', '컷 없는 원테이크', 'CONTINUOUS SINGLE TAKE the entire 30s. Digital pinch-zooms only (no cuts).',
                     '컷 대신 <b>줌만 쓰는 한 번의 촬영</b>처럼 만들면 진짜 누가 찍은 영상 같아요.'),
                    ('05', '15-05', '인물·배경을 목록으로 고정', 'LOCKED CAST: (인물 설명)\nLOCKED SET: (장소·차량·소품)',
                     '<b>"No second person"</b>처럼 나오면 안 되는 것까지 적어서 엉뚱한 사람이 끼어드는 걸 막아요.'),
                ],
            },
            {
                'who': '@Scenario_gg',
                'what': '같은 영상을 다른 각도로 다시 찍기',
                'tool': 'Seedance 2.5 영상→영상 · 위 AI / 아래 원본',
                'url': 'https://x.com/Scenario_gg/status/2102365054389899695',
                'shape': 'stack',
                'items': [
                    ('06', '15-06', '내 영상의 연기·타이밍은 그대로', 'Do not restage, re-perform, re-time or reinterpret it.',
                     '내가 찍은 영상을 @video1로 넣고 이 문장을 쓰면 <b>움직임과 말하는 타이밍은 원본 그대로</b>예요.'),
                    ('07', '15-07', '바뀌는 건 카메라뿐', 'The only variable is camera position and lens.',
                     '같은 순간을 <b>다른 자리의 카메라로 다시 찍은 것처럼</b>. 원작자는 한 테이크로 13개 앵글을 만들었어요.'),
                    ('08', '15-08', '원본과 같은 속도로', 'Real time, 1:1 with @video1. No speed ramps, added slow motion, freeze frames or time remaps.',
                     'AI가 멋대로 <b>슬로모션을 넣는 걸</b> 막아서 원본 오디오와 입 모양이 어긋나지 않아요.'),
                ],
            },
            {
                'who': '@RishuaVR',
                'what': '인도네시아 골목 브이로그',
                'tool': 'Seedance 2.5',
                'url': 'https://x.com/RishuaVR/status/2089204108175741157',
                'shape': 'wide',
                'items': [
                    ('09', '15-09', '끝까지 같은 사람으로', 'Maintain consistent identity, clothing, hairstyle, and appearance throughout the entire video.',
                     '먼저 <b>나이·옷·피부·머리 모양까지</b> 자세히 묘사하고 이 문장을 붙여요.'),
                    ('10', '15-10', '일부러 흔들리게', 'DV camcorder aesthetic. Heavy handheld shake, frequent autofocus hunting. No stabilization. No cinematic camera moves.',
                     '손떨림·초점 흔들림을 넣고 매끈한 카메라는 막아서 <b>친구가 찍어준 브이로그</b> 느낌.'),
                ],
            },
        ],
        'template': True,
    },
    {
        'slug': '14',
        'reel': 14,
        'part': 'PART 1',
        'title': 'AI 영상 고수들만 아는 프롬프트 치트키 5가지',
        'short': '홈비디오, 게임 화면, 초 단위 샷까지',
        'lede': '조회수 수백만 AI 영상 다섯 편의 공개 프롬프트에서, 공통으로 들어간 한 문장씩을 뽑았어요.',
        'hero': '14-hero',
        'hero_shape': 'wide',
        'stat': ('원작 북마크', '1.1만+'),
        'groups': [
            {'who': '@Sheldon056', 'what': '홈비디오', 'tool': 'Seedance 2.5', 'url': 'https://x.com/Sheldon056', 'shape': 'wide',
             'items': [('01', '14-01', '연출 없는 홈비디오처럼', 'documentary-style personal home video',
                        'spontaneous, imperfect를 같이 쓰면 <b>진짜 일상</b> 같아요.')]},
            {'who': '@_VVSVS', 'what': '게임 화면', 'tool': 'Midjourney 8.2 + Seedance 2.5', 'url': 'https://x.com/_VVSVS', 'shape': 'wide',
             'items': [('02', '14-02', '게임 화면처럼', 'gameplay capture, rigid follow camera, flat exposure, deep focus, no film grain',
                        '카메라를 <b>게임 카메라</b>로 묘사해요.')]},
            {'who': '@SyntheSarah', 'what': '4K 숲', 'tool': 'Seedance 2.5', 'url': 'https://x.com/SyntheSarah', 'shape': 'wide',
             'items': [('03', '14-03', '초 단위로 샷 나누기', '0-4s: wide shot / 4-8s: medium shot / 8-12s: close-up',
                        '한 영상 안에 <b>여러 컷이 자연스럽게</b> 이어져요.')]},
            {'who': '@laviniavelle', 'what': '구름 마을', 'tool': 'Seedance 2.5', 'url': 'https://x.com/laviniavelle', 'shape': 'wide',
             'items': [('04', '14-04', '끌어올리며 공개', 'slowly pull the camera upward and reveal',
                        '카메라가 올라가며 전체가 드러나서 <b>스케일이 커져요</b>.')]},
            {'who': '@AIwithkhan', 'what': '가면 군중', 'tool': 'Seedance 2.5', 'url': 'https://x.com/AIwithkhan', 'shape': 'wide',
             'items': [('05', '14-05', '참조 이미지로 인물 고정', 'use the uploaded images as exact visual references',
                        '참조 이미지를 정확한 기준으로 지정하면 <b>인물·의상이 안 바뀌어요</b>.')]},
        ],
        'template': False,
    },
]

TEMPLATE = """[STYLE + CAMERA]
Vertical 9:16 smartphone video. lived-in phone footage, not cinema, not HDR.
CONTINUOUS SINGLE TAKE the entire 10s. Digital pinch-zooms only (no cuts).

[LOCKED CAST]
(인물: 나이, 옷, 피부, 머리 모양까지 자세히)
Maintain consistent identity, clothing, hairstyle, and appearance throughout the entire video.

[LOCKED SET]
(장소: 배경, 소품, 날씨, 시간대)
(나오면 안 되는 것: No second person, No billboards…)

[TIMELINE]
0-3s: [HOOK] (첫 장면, 바로 눈길 끄는 사건)
3-7s: (전개)
7-10s: [IT GOES] (클라이맥스)

[AVOID]
No stabilization. No cinematic camera moves. No modern color grading."""
