"""Generate pixel-art SVG poses of 미리 from the reel character module -> miri.py (inline SVG strings)."""
import sys, json
sys.argv = ["x"]; sys.path.insert(0, "/home/claude/reel"); sys.path.insert(0, "/home/claude/char")
import numpy as np
from scipy import ndimage
import reel40f as R

OUTL = (28, 8, 20)

def grid(spec, t=0.0, eyes=None):
    mask = R.body_mask(spec, t)
    m = R.sdf_of(mask)[R.R // 2::R.R, R.R // 2::R.R] < 0
    G = R.G; px = np.zeros((G, G, 3), np.uint8); al = np.zeros((G, G), np.uint8)
    px[m] = R.P; al[m] = 1
    (ex, ey, gap), (sx, sy) = R.FACE[spec[0]]
    if eyes: R.draw_face(px, al, ex, ey, gap, eyes)
    R.draw_sprout(px, al, sx, sy)
    ol = ndimage.binary_dilation(al > 0, iterations=1) & (al == 0)
    px[ol] = OUTL; al[ol] = 1
    return px, al

def path_of(sel):
    """sel: bool GxG -> svg path of horizontal runs"""
    d = []
    for y in range(sel.shape[0]):
        x = 0; row = sel[y]
        while x < len(row):
            if row[x]:
                s = x
                while x < len(row) and row[x]: x += 1
                d.append(f"M{s} {y}h{x - s}v1h{s - x}z")
            else: x += 1
    return "".join(d)

def hexc(c): return "#%02x%02x%02x" % tuple(int(v) for v in c)

def pose(spec, t=0.0, eyesets=("idle", "blink", "happy")):
    base, al = grid(spec, t, None)
    layers = []
    colors = {}
    for y in range(64):
        for x in range(64):
            if al[y, x]: colors.setdefault(tuple(base[y, x]), []).append((y, x))
    for c, pts in colors.items():
        sel = np.zeros((64, 64), bool)
        for y, x in pts: sel[y, x] = True
        layers.append(f'<path fill="{hexc(c)}" d="{path_of(sel)}"/>')
    faces = []
    for e in eyesets:
        p2, a2 = grid(spec, t, e)
        diff = np.any(p2 != base, axis=2) & (a2 > 0)
        faces.append(f'<path class="e e-{e}" fill="#140c12" d="{path_of(diff)}"/>')
    ys, xs = np.nonzero(al)
    return {"body": "".join(layers), "face": "".join(faces), "bbox": [int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1]}

POSES = {
    "idle": (("idle", {}), 0.0),
    "wave": (("wave", {}), 0.12),
    "wave2": (("wave", {}), 0.42),
    "cheer": (("cheer", {}), 0.0),
    "cheer2": (("cheer", {}), 0.11),
    "sit": (("sit", {}), 0.0),
    "melt": (("melt", {}), 0.0),
    "hop": (("hop", {}), 0.0),
    "point": (("point", {"ang": -35}), 0.0),
    "think": (("think", {}), 0.0),
    "mag": (("mag", {"ang": -40}), 0.0),
    "ball": (("ball", {}), 0.0),
}
out = {k: pose(s, t) for k, (s, t) in POSES.items()}
with open("/home/claude/site/miri.py", "w") as f:
    f.write("# generated by make_miri.py\nMIRI = " + json.dumps(out, ensure_ascii=False) + "\n")
print({k: v["bbox"] for k, v in out.items()}, sum(len(v["body"]) + len(v["face"]) for v in out.values()))
